apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: us-central1-docker.pkg.dev/agenticai-demo-vertex/node-app-repo/node-app:latest
        ports:
        - containerPort: 8080
