name: Agentic-Heal
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  workflow_dispatch:

jobs:
  heal:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run && github.event.workflow_run.conclusion == 'failure') }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write

    steps:
      # Checkout the exact SHA that failed (workflow_run) or the current ref (manual)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      # Download CI logs from the *failed CI run* (only when triggered by workflow_run)
      - name: Download CI logs (from failed CI run)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/download-artifact@v4
        with:
          name: ci-logs
          path: ./ci-logs
          run-id: ${{ github.event.workflow_run.id }}
        continue-on-error: true

      # Fallback for manual runs (no run-id context)
      - name: Download CI logs (manual fallback)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/download-artifact@v4
        with:
          name: ci-logs
          path: ./ci-logs
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r agents/requirements.txt

      - name: Auth & env
        run: |
          KEY="$RUNNER_TEMP/gcp-key.json"
          echo '${{ secrets.GCP_SA_KEY }}' > "$KEY"
          chmod 600 "$KEY"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$KEY" >> $GITHUB_ENV
          echo "GCP_PROJECT=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "GCP_LOCATION=${{ secrets.GCP_LOCATION }}" >> $GITHUB_ENV
          echo "VERTEX_MODEL=${{ secrets.VERTEX_MODEL }}" >> $GITHUB_ENV
          echo "GH_BOT_ACTOR=agentic-bot" >> $GITHUB_ENV
          echo "GH_BOT_EMAIL=agentic-bot@example.com" >> $GITHUB_ENV

      - name: Run MCP server plan
        run: |
          python agents/mcp_server.py
