name: Agentic-Heal
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  heal:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download CI logs
        uses: actions/download-artifact@v4
        with:
          name: ci-logs
          path: ./ci-logs
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r agents/requirements.txt

      - name: Auth & env
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp-key.json" >> $GITHUB_ENV
          echo "GCP_PROJECT=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "GCP_LOCATION=${{ secrets.GCP_LOCATION }}" >> $GITHUB_ENV
          echo "VERTEX_MODEL=${{ secrets.VERTEX_MODEL }}" >> $GITHUB_ENV
          echo "GH_BOT_ACTOR=agentic-bot" >> $GITHUB_ENV
          echo "GH_BOT_EMAIL=agentic-bot@example.com" >> $GITHUB_ENV

      - name: Run MCP server plan
        run: |
          python agents/mcp_server.py
