name: Agentic-Heal

on:
  workflow_run:
    # IMPORTANT: this must match your CI workflow's 'name:' EXACTLY
    workflows: ["CI (main-only, self-heal)"]
    types: [completed]
  workflow_dispatch:

jobs:
  heal:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run && github.event.workflow_run.conclusion == 'failure') }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write

    steps:
      # Checkout the exact SHA that failed (workflow_run) or current ref (manual)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      # Download CI logs (from failed CI run)
      - name: Download CI logs (from failed CI run)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/download-artifact@v4
        with:
          name: ci-logs
          path: ./ci-logs
          run-id: ${{ github.event.workflow_run.id }}
        continue-on-error: true

      # Fallback for manual runs (no run-id context)
      - name: Download CI logs (manual fallback)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/download-artifact@v4
        with:
          name: ci-logs
          path: ./ci-logs
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Provide bot identity (used by the healer to commit/push)
      - name: Set env for healer
        run: |
          echo "GH_BOT_ACTOR=agentic-bot" >> $GITHUB_ENV
          echo "GH_BOT_EMAIL=agentic-bot@example.com" >> $GITHUB_ENV

      - name: Run smarter healer
        run: |
          python agents/mcp_server.py

