name: Agentic-Heal
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  heal:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download CI logs
        uses: actions/download-artifact@v4
        with:
          name: ci-logs
          path: ./ci-logs
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install agent deps
        run: |
          python -m pip install -r agents/requirements.txt

      - name: Triage logs with Vertex
        id: triage
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_LOCATION: ${{ secrets.GCP_LOCATION }}
          VERTEX_MODEL: ${{ secrets.VERTEX_MODEL }} # e.g., gemini-1.5-pro
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
          LOGFILE=$(ls ci-logs/*.xml 2>/dev/null | head -n1 || true)
          if [ -z "$LOGFILE" ]; then LOGFILE=/dev/null; fi
          python agents/log_triage.py > triage.json
          echo "triage_text<<EOF" >> $GITHUB_OUTPUT
          cat triage.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Prepare repo snapshot
        id: snap
        run: |
          {
            echo "repo_snapshot<<EOF"
            echo "=== app/src/server.js ==="
            sed -n '1,250p' app/src/server.js
            echo
            echo "=== app/__tests__/health.test.js ==="
            sed -n '1,250p' app/__tests__/health.test.js 2>/dev/null || true
            echo "=== app/tests/health.test.js ==="
            sed -n '1,250p' app/tests/health.test.js 2>/dev/null || true
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Ask Vertex for a patch (unified diff)
        id: propose
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_LOCATION: ${{ secrets.GCP_LOCATION }}
          VERTEX_MODEL: ${{ secrets.VERTEX_MODEL }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
          TRIAGE_TEXT: ${{ steps.triage.outputs.triage_text }}
          REPO_SNAPSHOT: ${{ steps.snap.outputs.repo_snapshot }}
        run: |
          python agents/fix_suggest.py > diff.json
          echo "patch_diff<<EOF" >> $GITHUB_OUTPUT
          jq -r '.diff' diff.json >> $GITHUB_OUTPUT || true
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Apply patch, run tests, and open PR if green
        id: apply
        env:
          PATCH_DIFF: ${{ steps.propose.outputs.patch_diff }}
          GH_BOT_ACTOR: "agentic-bot"
          GH_BOT_EMAIL: "agentic-bot@example.com"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python agents/error_fix.py > result.json || true
          cat result.json

